---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - repositories

repositories:
- ROCKET repo:
    type: git
    url: "https://github.com/chandrasekar160598/mavenprojectwar.git"
    branch: master
