---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      -  sh "git clone https://github.com/chandrasekar160598/mavenprojectwar.git"
